spec_version: 1
kind: blueprint
metadata:
  description: >
    Application is configured to deploy with multiple instances for load tests.
    
clouds: 
  - AWS: us-west-1
  
artifacts:
  - leadeasy-frontend: latest/leads-webapp.latest.tar.gz
  - salesforce-virt: sf-virtual-service/leads-virt.war

inputs:
- AWS_INSTANCE_TYPE: m5.large

applications:
  - leadeasy-frontend:
      instances: 2
      input_values:
        - AWS_INSTANCE_TYPE: $AWS_INSTANCE_TYPE
        - SALESFORCE_LOGIN_URL: http://salesforce-virt.${COLONY.SandboxId}.sandbox.com:8080/leads-virt
    
  - database:      
      input_values:
        - AWS_INSTANCE_TYPE: $AWS_INSTANCE_TYPE

  - salesforce-virt:
            
debugging:
  availability: on